# Generated by Django 5.2.5 on 2025-09-17 03:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('sepak_bola', 'Sepak Bola'), ('jersey', 'Jersey'), ('sepatu', 'Sepatu'), ('pelindung', 'Pelindung'), ('lainnya', 'Lainnya')], default='sepak_bola', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('reviews', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
