# Generated by Django 5.2.5 on 2025-09-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('ball_type', models.CharField(max_length=50)),
                ('is_official_match_ball', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=50)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('reviews', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
