# Generated by Django 5.2.5 on 2025-09-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pemainbola'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PemainBola',
        ),
    ]
