# Generated by Django 5.2.5 on 2025-09-17 02:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sepak_bola', 'Sepak Bola'), ('jersey', 'Jersey'), ('sepatu', 'Sepatu'), ('pelindung', 'Pelindung'), ('lainnya', 'Lainnya')], default='sepak_bola', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
