# Generated by Django 5.2.5 on 2025-09-17 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_category_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ball_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_official_match_ball',
        ),
    ]
